### ISSUE TITLE
Reloading JEI causes a CMod crash

### ISSUE THREAD

**Issue by TheComputerizer** [friendlyhj/ZenRecipeReloading#11]
As you can see [in this log](https://mclo.gs/i5gCOCy) after running `/ct jeiReload` I get a few tooltip errors that do not show up when the game is initially started and then a CMod crash which freezes my game. This might be due to the fact that I am using HEI rather than JEI and I have not had time to do much testing regarding that or maybe its just the large number of recipes in my pack. Here are the relevant mod versions I was using:
```
CT: 1.12.2-4.1.20.697
ZenUtils: 1.16.3
ZRR: 1.1.5
HEI: 1.12.2-4.25.1
```
Here if the [full log](https://mclo.gs/fD4wt04#L10808) if you need it and here is my [jei/jei.cfg](https://hastebin.com/share/seguceboze.graphql) file. My scripts are also [here](https://github.com/TheComputerizer/Dimension-Hopper-The-Fall/tree/main/scripts) if you need them

**Comment by friendlyhj** [comment]
I wonder why the server was stopped. Anyway, try `v1.2.0`, which adds progress bar while reloading JEI to avoid window freeze.

**Comment by TheComputerizer** [comment]
I tried `v1.2.0` and it showed the bar and things seemed to load correctly, but once the bar was done and it seemed to finish reloading I got the same freeze/crash

**Comment by friendlyhj** [comment]
:concerned: Can you post the new log?

**Comment by TheComputerizer** [comment]
Here is the [log](https://mclo.gs/e56o0lP). The current issue might not be what I thought it was but the freeze/crash does still happen

**Comment by friendlyhj** [comment]
[zenrecipereload-1.2.1.zip](https://github.com/friendlyhj/ZenRecipeReloading/files/13838095/zenrecipereload-1.2.1.zip)
Try this?

**Comment by TheComputerizer** [comment]
That seems to give me [this mixin crash](https://mclo.gs/rqyPrCd)

**Comment by friendlyhj** [comment]
Oh, I typed wrong reference map name. missing `ing`
[zenrecipereloading-1.2.1.zip](https://github.com/friendlyhj/ZenRecipeReloading/files/13839998/zenrecipereloading-1.2.1.zip)

**Comment by TheComputerizer** [comment]
I can confirm that I was able to startup and run `/ct jeiReload` without my game crashing for the first time. Even the tooltip errors are gone now too.
