### ISSUE TITLE
沉浸热重载报错

### ISSUE THREAD

**Issue by skrjii** [friendlyhj/ZenRecipeReloading#12]
只有报错 但是魔改可正常生效

immer  56~64 行
[新建文件夹 (2).zip](https://github.com/friendlyhj/ZenRecipeReloading/files/14893775/2.zip)

**Comment by skrjii** [comment]
https://mclo.gs/RcHfZca

**Comment by friendlyhj** [comment]
日志

**Comment by skrjii** [comment]
https://mclo.gs/APhYYhT
