### ISSUE TITLE
InWorldCrafting兼容性

### ISSUE THREAD

**Issue by zfms4188** [friendlyhj/ZenRecipeReloading#14]
InWorldCrafting: https://www.mcmod.cn/class/1916.html
重载并jei重载后,修改前的配方不会被删除,且依旧有效
但是新配方也可以生效

若重载的脚本内含有此mod的语法,则每重载一次都会添加一个该语法的配方 （表现在jei重复出现配方

**Comment by friendlyhj** [comment]
与 #2 重复，模组的兼容只能一个个加，所以如果你要的模组不支持重载，就不要重载修改它的脚本。这就是为啥默认脚本不能重载的原因。

**Comment by friendlyhj** [comment]
看模组本身代码的具体实现，它是否走了 CraftTweaker 的 `IAction` api，这个也并非强制。如果是，zenutils 会发现并阻止重复添加配方。但 IWC 并没有走，所以就这样了。我最近在本地写了它的兼容，但还没发布。

**Comment by zfms4188** [comment]
> 看模组本身代码的具体实现，它是否走了 CraftTweaker 的 `IAction` api，这个也并非强制。如果是，zenutils 会发现并阻止重复添加配方。但 IWC 并没有走，所以就这样了。我最近在本地写了它的兼容，但还没发布。

半个月过去了,何时准备发布兼容版本呢 XD
