### ISSUE TITLE
jeiReload和沉浸智能的冲突

### ISSUE THREAD

**Issue by zfms4188** [friendlyhj/ZenRecipeReloading#16]
1.使用jei重载后，沉浸智能的jei配方会无法显示。
https://www.mcmod.cn/class/2756.html

2.一个脚本文件,使用了沉浸智能的语法,且没有添加 reloadable
使用/ct reload后 同脚本下的其他语法失效
例如我在里面删除了铁齿轮的配方 ct reload后就失效了

(#reload的脚本下未使用沉浸智能的语法也会如此)
(另外 似乎不支持原版的tips和名称修改的重载？)

**Comment by friendlyhj** [comment]
readme 也没说支持沉浸智能和 tooltip 名称的修改啊。
由于无法确认哪个修改是哪个脚本写的，/ct reload 会回滚所有修改，请保证所有工作台合成修改的代码都在重载脚本范围内。
如果是 tooltip，可以使用 zenutils 的 `modfiyTooltip`，这个是可以热重载的。没写文档，你可以看看 probezs 的生成。

**Comment by zfms4188** [comment]
> readme 也没说支持沉浸智能和 tooltip 名称的修改啊。 由于无法确认哪个修改是哪个脚本写的，/ct reload 会回滚所有修改，请保证所有工作台合成修改的代码都在重载脚本范围内。 如果是 tooltip，可以使用 zenutils 的 `modfiyTooltip`，这个是可以热重载的。没写文档，你可以看看 probezs 的生成。

删除失效的原因明白了。也就是能重载的内容,一定要写在reloadable下

可沉浸智能的脚本内容,我后续将可重载内容移出后,脚本文件只剩下沉浸智能的语法,然后也没有添加reloadable,重启游戏,使用/ct jeiReload后,沉浸智能的jei合成全部无法查询,它自带的配方也没了

我删除了沉浸智能的脚本,重启游戏,使用/ct jeiReload,沉浸智能的jei合成消失  (
