### ISSUE TITLE
Errors with Extended Crafting & Artisan Worktables

### ISSUE THREAD

**Issue by TheComputerizer** [friendlyhj/ZenRecipeReloading#7]
It seems like this mod causes issues with the `TableCrafting#remove` action, even if the script file is explicitly defined as `#notreloadable` [this](https://mclo.gs/Jm4OItX) is the error I get for that. The script I used to test is a simple `mods.extendedcrafting.TableCrafting;.remove(<extendedcrafting:material:24>)`. When I try using `/ct reload` the command fails with [this mixin error](https://mclo.gs/zWUNbSv)

On a separate note, I get [this weird truncated class file error](https://mclo.gs/SCx2rpu) with my [basic worktable](https://hastebin.com/share/yotanidito.less) script.

Both seem to work fine without the mod and `/ct syntax` doesn't complain about anything

**Comment by friendlyhj** [comment]
1. Are your Extended Crafting is nomifactory version?
2. Try this version
[zenrecipereload-1.1.3.zip](https://github.com/friendlyhj/ZenRecipeReloading/files/13398813/zenrecipereload-1.1.3.zip)

**Comment by TheComputerizer** [comment]
I wasn't aware of the nomi version of extended crafting and updating to that seems to have fixed the first issue. The truncated class file thing seems to still be an issue, but I'm not 100% sure whether its my script breaking or not

**Comment by friendlyhj** [comment]
Released `v1.1.4` to fix the first issue. This mod should only compat with the nomifactory version.

The stacktrace shows the error is from your script. But I can't find what is wrong. Can you update complie bytecode? Add debug preprocessor, then it will be output at `generated` dir.

**Comment by TheComputerizer** [comment]
I figured out it didn't seem to like my my tableExtra util method, maybe since it had too many parameters. The initial script loading and reloading seems to be working as intended now that I've updated to the nomifactory version of extended crafting and ZRR 1.1.4, but running `/ct jeiReload` seems to give me a [class cast exception](https://mclo.gs/VsYbXFk) related to entity age. Not sure how viable debugging that would be since it could just be a compatibility error but since it doesn't seem to be related to the initial issues I'll close it
